apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  player_initial_lives: "3"
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5    


---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod
spec:
  containers:
    - name: demo
      image: alpine
      command: ['sh', '-c', 'while true; do echo player_initial_lives: $PLAYER_INITIAL_LIVES; echo game_properties: $GAME_PROPERTIES; sleep 1; done']
      env:
        - name: PLAYER_INITIAL_LIVES 
          valueFrom:
            configMapKeyRef:
              name: game-demo
              key: player_initial_lives

        - name: GAME_PROPERTIES
          valueFrom:
            configMapKeyRef:
              name: game-demo
              key: game.properties
