apiVersion: batch/v1
kind: CronJob
metadata:
  name: myjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: nginx
            command:
            - /bin/sh
            - -c
            - curl myapp
          restartPolicy: OnFailure
