apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp
spec:
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      # restartPolicy: Always
      containers:
      - name: goapp
        image: devopsaes/probecheck:2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: SLEEP_TIME
          value: "5"  

        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 7
          periodSeconds: 5
          failureThreshold: 1
        # readinessProbe:
        #   httpGet:
        #     path: /ready
        #     port: 8080
        #   initialDelaySeconds: 7
        #   periodSeconds: 5
          

---
apiVersion: v1
kind: Service
metadata:
  name: goapp
spec:
  type: NodePort
  selector:
    app: goapp
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000