# [test]
# 172.17.17.50 ansible_user=master  ansible_password=master 

[test]
172.17.17.50 ansible_user=master  ansible_password=master ansible_become_password=master 



; | Variable                  | Purpose       | Used For                 | Example Command Equivalent |
; | ------------------------- | ------------- | ------------------------ | -------------------------- |
; | `ansible_password`        | SSH password  | Logging into remote host | `ssh master@172.17.17.50`  |
; | `ansible_become_password` | Sudo password | Running commands as root | `sudo <command>`           |
