apiVersion: v1
kind: Service
metadata:
  namespace: {{ quote .Values.Global.Namepace }}
  name: {{ quote .Values.Deployment.Name }}
spec:
  selector:
    app: {{ quote .Values.Deployment.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.Deployment.Port }}
      targetPort: {{ .Values.Deployment.Port }}
  type: {{ .Values.Service.Type }}
