apiVersion: v1
kind: Pod
metadata:
  name: load-generator
  namespace: default
spec:
  containers:
  - name: load-generator
    image: busybox:1.28
    command:
    - /bin/sh
    - -c
    - "while sleep 0.01; do wget -q -O- http://php-apache; done"
  restartPolicy: Never
