apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: akif #cluster name
  region: ap-south-1 #desired region
nodeGroups:
  - name: ng-1 #cluster node group name
    instanceType: t3.large #desired instance type
    desiredCapacity: 2 #desired nodes count / capacity
    ssh:
      allow: false # if true - will use ~/.ssh/id_rsa.pub as the default ssh key
