apiVersion: apps/v1
kind: Deployment
metadata:
  name: hecker-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hecker
  template:
    metadata:
      labels:
        app: hecker
    spec:
      containers:
      - name: hecker-container
        image: nginx
        ports:
        - containerPort: 80
