pipeline {
    agent any


    stages {

        stage('Checkout') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'github', passwordVariable: 'passwd', usernameVariable: 'username')]) {

                git branch: 'main', url: "https://$username:$passwd@github.com/aakkiiff/jj.git"
   
                }
                }
            }

        stage('Terraform Apply') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'aws', passwordVariable: 'AWS_SECRET_ACCESS_KEY', usernameVariable: 'AWS_ACCESS_KEY_ID')]) {
                sh 'terraform init'
                sh 'terraform apply -auto-approve'
                }
            }
        }
        }

}
