apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: busybox-logger
  namespace: default
spec:
  selector:
    matchLabels:
      app: busybox-logger
  template:
    metadata:
      labels:
        app: busybox-logger
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
        - while true; do 
            echo "Hello from BusyBox on $(NODE_NAME)"; 
            sleep 5; 
          done;
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
