FROM ubuntu:20.04

# Update, Install, noninterative promp while package installation
# remove cache package ->-> reduce file size
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    openjdk-11-jre wget && \
    rm -rf /var/lib/apt/lists/*
    
# Download latest Jenkins war file
RUN wget -O /opt/jenkins.war https://updates.jenkins-ci.org/latest/jenkins.war

# Jenkins home dir
RUN mkdir /var/jenkins_home

# Jenkins port
EXPOSE 8080

# Jenkins home directory as an environment variable
ENV JENKINS_HOME /var/jenkins_home

# Run jenkins -> -> ->
CMD ["java", "-jar", "/opt/jenkins.war"]
