apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cm-app
  template:
    metadata:
      labels:
        app: cm-app
    spec:
      containers:
      - image: alpine
        name: cm-container
        command: ['sh', '-c', 'while true; do echo $NAME; sleep 1; done']
        env:
        - name: NAME
          valueFrom:
            configMapKeyRef:
              name: name-config
              key: name
