---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
  namespace: minio
spec:
  storageClassName: 'nfs-client'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "10Gi"
