apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: akif
rules:

  # Full access to Pods
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: akif
subjects:
  - kind: User  
    name: akif
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: akif
  apiGroup: rbac.authorization.k8s.io
