apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  template:
    spec:
      containers:
      - name: testjob
        image: mysql:8.0
        command:
        - "/bin/sh"
        - "-c"
        - >
          mysqldump -h mysql-service -u$MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE;
        env:
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "rootpassword"
        - name: MYSQL_DATABASE
          value: "exampledb"

      restartPolicy: Never
