---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: monitoring
  name: compactor
spec:
  storageClassName: 'nfs-client'
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 20Gi
