---
- hosts: test
  become: true
  gather_facts: false
  tasks:
    - name: Install apache httpd
      ansible.builtin.apt:
        name: apache2
        state: absent
        update_cache: yes
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html
        owner: root
        group: root
        mode: '0644'